# Generated by Django 5.2.6 on 2025-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ilce',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Aynı e-posta ile ikinci bir kullanıcı olamaz.', max_length=254, unique=True, verbose_name='Email (tekil)'),
        ),
    ]
